<?php

/**
 * AceptedProviderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AceptedProviderStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AceptedProviderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AceptedProviderState');
    }
}