<?php

/**
 * BasketProviderProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grupos_consumo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BasketProviderProduct extends BaseBasketProviderProduct
{
  public function getBasketSlug()
  {
    $basket=Doctrine::getTable("ProviderProduct")->findOneById($this->basket_id);
    
    return $basket->slug;
  }
}
