<?php

/**
 * BasketProviderProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BasketProviderProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BasketProviderProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BasketProviderProduct');
    }
}