<?php

/**
 * CategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    public static function getCategoryList(){
        $query=Doctrine::getTable("Category")
        ->findAllSorted('ASCENDING');

        return $query;
    }

    public static function getNewsList($categoryId,$limit){
        $query=Doctrine::getTable("News")
        ->createQuery("a")
        ->where("category_id=?",$categoryId)
        ->orderBy("position desc")
        ->limit($limit)
        ->execute();

        return $query;
    }

    public static function getModelList($model,$categoryId,$limit){
        $query=Doctrine::getTable($model)
        ->createQuery("a")
        ->where("category_id=?",$categoryId)
        ->orderBy("position desc")
        ->limit($limit)
        ->execute();

        return $query;
    }
}