<?php

/**
 * Category
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    palestina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function getCulture(){
        return sfContext::getInstance()->getUser()->getCulture();
    }

    public function getCultureTranslation(){
        return sfContext::getInstance()->getUser()->getFlash("cultureTranslation");
    }

    public function setCultureTranslation($cultureTranslation){
        $this->cultureTranslation=$cultureTranslation;
    }

    public function getNewsList($limit){

        return CategoryTable::getNewsList($this->id,$limit);
    }

    public function getImage()
    {
        return $this->getImageCategory();
    }

    public function getModelList($model, $limit){

        return CategoryTable::getModelList($model,$this->id,$limit);
    }

    public function hasNews(){
        $count=count(CategoryTable::getNewsList($this->id,1));
        if ($count)
        {
            return true;
        }

        return false;
    }

    public function getShortDescription($max=200)
    {

        return strip_tags(substr($this->description,0,$max)."...","<p>");
    }

    public function getRandGalery()
    {
        $galery=$this->getGalery();
        $index=rand(0,count($this->getGalery())-1);

        return $galery[$index];
    }

    public function getRand($model)
    {
        $galery=call_user_func(array($this,"get{$model}"));
        $index=rand(0,count($galery)-1);
        return $galery[$index];
    }

    /*
     * Para saber si tiene algún contenido del modelo dado
     */
    public function has($model)
    {
        $count=count(CategoryTable::getModelList($model,$this->id,1));
        if ($count)
        {
            return true;
        }

        return false;
    }

}
