<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }
    
    public function getCityList($pk)
    {
        return Doctrine_Core::getTable('City')
        ->createQuery('c')        
        ->leftJoin("c.Translation t")
        ->select("c.id, t.name")      
        ->where("state_id=?",$pk)  
        ->execute();
    }
}