<?php

/**
 * ConsumerOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsumerOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsumerOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConsumerOrder');
    }
}