<?php

/**
 * ConsumerGroupStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsumerGroupStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsumerGroupStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConsumerGroupState');
    }
}