<?php

/**
 * ConsumerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsumerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsumerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Consumer');
    }
    
    public function consumerInGroup()
    {
        return $query=Doctrine::getTable("Consumer")->createQuery()
            ->where("consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->consumer_group_id)
            ->andWhere("consumer_state_id=?",2);            
    }
}