<?php

/**
 * ConsumerOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsumerOrderStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsumerOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConsumerOrderState');
    }
}