<?php

/**
 * ConsumerStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsumerStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsumerStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConsumerState');
    }
}