<?php

/**
 * Event
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    palestina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent
{
  var $day;
  var $month;
  var $year;

  public function getCulture()
  {
    return sfContext::getInstance()->getUser()->getCulture();
  }

  public function getCultureTranslation()
  {
    return sfContext::getInstance()->getUser()->getFlash("cultureTranslation");
  }

  public function setCultureTranslation($cultureTranslation)
  {
    $this->cultureTranslation=$cultureTranslation;
  }

  public function getDay()
  {
    list($y, $m, $d) = explode('-', $this->date);
    $this->day=$d;

    return $this->day;
  }

  public function isInHome(){
    $query=Doctrine::getTable("Home")->findByObjectIdAndObjectClass($this->id,$this->getModel());

    if (count($query)){
      return true;
    }

    return false;
  }

  public function getModel(){

    return "Event";
  }

  public function getAllDay()
  {
    if ($this->end_date)
    {
      return false;
    }

    return true;
  }

  public function getRealDate()
  {
    return  date('Y-m-d\TH:i:sP', strtotime("$this->date $this->time"));
  }

  public function getRealEndDate()
  {
    if ($this->end_date)
    {
      return  date('Y-m-d\TH:i:sP', strtotime("$this->end_date"));
    }

    return false;
  }

}
