<?php

/**
 * EventCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventCategory');
    }

    public function applyNameFilter($query, $value)
    {
        $query->leftJoin($query->getRootAlias() . '.Translation t')
        ->addWhere('t.name like \'%' . $value['text'] . '%\'');
    }
}