<?php

/**
 * Home
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    webs_proyectos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Home extends BaseHome
{
    public function getObjectName(){
        $object=$this->getObject();

        return $object->name;
    }

    public function getObject(){
        $query=Doctrine::getTable($this->object_class)
        ->createQuery("a")
        ->where("id=?",$this->object_id)
        ->execute();
        $object=$query[0];

        return $object;
    }

    public function getType(){
        switch ($this->object_class) {
            case "News":
                return __("Noticia");
                break;
            case "Galery":
                return __("Galería");
                break;
            case "Landing":
                return __("Pág. Estática");
                break;
            case "Folder":
                return __("Carpeta");
                break;
            case "Video":
                return __("Vídeo");
                break;
            case "Link":
                return __("Enlace");
                break;
        }

    }
}
