<?php

/**
 * HomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HomeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Home');
    }
}