<?php

/**
 * ImageGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageGroup');
    }
}