<?php

/**
 * InternalClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InternalClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InternalClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InternalClass');
    }
    
    /*
     * En el formulario de creación de usuarios del frontend, sólo se usan los usuarios internos de nivel 1 
     */
    public function getPublicClass()
    {
        return $query=self::getInstance()->createQuery()->where("level=1")->orderBy("position asc");
    }
}