<?php

/**
 * InvitationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvitationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvitationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvitationStatus');
    }
}