<?php

/**
 * LandingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LandingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LandingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Landing');
    }
}