<?php

/**
 * LinkCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    palestina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LinkCategory extends BaseLinkCategory
{
    public function getCulture()
    {
        return sfContext::getInstance()->getUser()->getCulture();
    }

    public function getCultureTranslation()
    {
        return sfContext::getInstance()->getUser()->getFlash("cultureTranslation");
    }

    public function setCultureTranslation($cultureTranslation)
    {
        $this->cultureTranslation=$cultureTranslation;
    }

    public function getLinks()
    {
        return count($this->Link);
    }

    public function isInHome(){
        $query=Doctrine::getTable("Home")->findByObjectIdAndObjectClass($this->id,$this->getModel());

        if (count($query)){
            return true;
        }

        return false;
    }

    public function getModel(){

        return "LinkCategory";
    }

    public function getShortContent($max=200)
    {
        return strip_tags(substr($this->content,0,$max)."...","<p>");
    }

    public function hasLinks(){
        $count=count(LinkCategoryTable::getLinksList($this->id,1));
        if ($count)
        {
            return true;
        }

        return false;
    }
    
    public function getDateCreatedAt()
    {
      $date=strtotime($this->getCreatedAt());
    
      return date("Y-m-d",$date);
    }
}
