<?php

/**
 * Link
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    palestina
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Link extends BaseLink
{
    public function getCulture()
    {
        return sfContext::getInstance()->getUser()->getCulture();
    }

    public function getCultureTranslation()
    {
        return sfContext::getInstance()->getUser()->getFlash("cultureTranslation");
    }

    public function setCultureTranslation($cultureTranslation)
    {
        $this->cultureTranslation=$cultureTranslation;
    }

    public function getShortName()
    {
        if (strlen($this->name)>30){

            return strip_tags(substr($this->name,0,30)."...");
        }

        return $this->name;
    }

    public function isInHome(){
        $query=Doctrine::getTable("Home")->findByObjectIdAndObjectClass($this->id,$this->getModel());

        if (count($query)){
            return true;
        }

        return false;
    }

    public function getModel(){

        return "Link";
    }
    
    public function getDateCreatedAt()
    {
      $date=strtotime($this->getCreatedAt());
    
      return date("Y-m-d",$date);
    }
}
