<?php

/**
 * MapObjectTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapObjectTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapObjectTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapObjectType');
    }
}