<?php

/**
 * OrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderState');
    }
}