<?php

/**
 * ProductionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductionTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductionType');
    }
}