<?php

/**
 * ProductSizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSizeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSizeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSize');
    }
}