<?php

/**
 * ProductSubcategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSubcategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSubcategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSubcategory');
    }

    public function getSubcategoryList($pk)
    {
        return Doctrine_Core::getTable('ProductSubcategory')
        ->createQuery('c')
        ->where("product_category_id=?",$pk)
        ->leftJoin("c.Translation t")
        ->orderBy("t.name")
        ->execute();
    }
}