<?php

/**
 * ProductCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategory');
    }

    public function getCategoryList()
    {
        return Doctrine_Core::getTable('ProductCategory')
        ->createQuery('c')
        ->leftJoin("c.Translation t")
        ->where("id <>?",10) //para que no salgan las cestas de productos
        ->orderBy("t.name")
        ->execute();
    }

    public function getCategoryListHome()
    {
        return Doctrine_Core::getTable('ProductCategory')
        ->createQuery('c')
        ->leftJoin("c.Translation t")        
        ->orderBy("t.name")
        ->execute();
    }
}