<?php

/**
 * ProductCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    grupos_consumo
 * @subpackage model
 * @author     info@diphda.net
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductCategory extends BaseProductCategory
{
    public function getCulture(){
        return sfContext::getInstance()->getUser()->getCulture();
    }

    public function getCultureTranslation(){
        return sfContext::getInstance()->getUser()->getFlash("cultureTranslation");
    }

    public function setCultureTranslation($cultureTranslation){
        $this->cultureTranslation=$cultureTranslation;
    }

    /*
     * esta función devuelve las subcategorías de producto de la categoría
     * de las cuales, el proveedor tiene productos.
     * Es para el catálogo.
     */

    public function getSubcategoryProvider($provider_id)
    {
        $query=Doctrine::getTable("ProviderProduct")
        ->createQuery()
        ->where("provider_id=?",$provider_id)
        ->andWhere("product_category_id=?",$this->id)
        ->andWhere("is_active=?",1)
        ->execute();

        $array_subcategories=array();
        foreach ($query as $provider_product)
        {
            $array_subcategories[]=$provider_product->product_subcategory_id;
        }

        return Doctrine::getTable("ProductSubcategory")->createQuery()->whereIn("id",$array_subcategories)->orderBy("id")->execute();
    }
}
