<?php

/**
 * ProviderShippingModeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProviderShippingModeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProviderShippingModeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProviderShippingMode');
    }
}