<?php

/**
 * ProviderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProviderStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProviderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProviderState');
    }
}