<?php

/**
 * ProviderTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProviderTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProviderTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProviderType');
    }
}