<?php

/**
 * ProviderProductTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProviderProductTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProviderProductTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProviderProductType');
    }
}