<?php

/**
 * PurchaseUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PurchaseUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseUnit');
    }
}