<?php

/**
 * TierPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TierPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TierPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TierPrice');
    }
}