<?php

/**
 * sfSimpleForumForumTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumForumTable extends PluginsfSimpleForumForumTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumForumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumForum');
    }

    public function getAllByConsumerGroup($id)
    {
        $q = $this->createQuery();
        $q->where("consumer_group_id=?",$id);
        $q->orderBy('sfSimpleForumForum.sfSimpleForumCategory.rank ASC, rank ASC');

        return $q->execute();
        // doSelectJoinCategoryLeftJoinPost
    }
}