<?php

/**
 * sfSimpleForumRecommandationLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumRecommandationLogTable extends PluginsfSimpleForumRecommandationLogTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumRecommandationLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumRecommandationLog');
    }
}