<?php

/**
 * sfSimpleForumCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumCategoryTable extends PluginsfSimpleForumCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumCategory');
    }
}