<?php

/**
 * sfSimpleForumAbuseLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumAbuseLogTable extends PluginsfSimpleForumAbuseLogTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumAbuseLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumAbuseLog');
    }
}