<?php

/**
 * sfSimpleForumRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumRankTable extends PluginsfSimpleForumRankTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumRank');
    }
}