<?php

/**
 * sfSimpleForumTopicViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumTopicViewTable extends PluginsfSimpleForumTopicViewTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumTopicViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumTopicView');
    }
}