<?php

/**
 * sfSimpleForumTopicTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumTopicTable extends PluginsfSimpleForumTopicTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumTopic');
    }

    public function getLatestCriteria()
    {
        /*
         * Con esta condición controlo si hay que devolver la consulta sólo para los foros del grupo
         * de consumo o
         */
        if (sfContext::getInstance()->getUser()->getAttribute("forum_type")=="consumer_group")
        {
            $q = $this->createQuery("a");
            $q->leftJoin("a.sfSimpleForumForum c");
            $q->where("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
            $q->orderBy('id DESC');

            return $q;
        }
        else
        {
            $q = $this->createQuery();
            $q->orderBy('updated_at DESC');

            return $q;
        }
    }

    public function getForUserCriteria($user_id)
    {
        if (sfContext::getInstance()->getUser()->getAttribute("forum_type")=="consumer_group")
        {
            $q = $this->createQuery("a");
            $q->leftJoin("a.sfSimpleForumForum c");
            $q->where('a.user_id = ?', array($user_id));
            $q->andWhere("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
            $q->orderBy('updated_at DESC');

            return $q;
        }
        else
        {
            $q = $this->createQuery();
            $q->where('user_id = ?', array($user_id));
            $q->orderBy('updated_at DESC');

            return $q;
        }
       
    }

    public function getAllPostUserInConsumerGroup($user_id) {
        $q = $this->createQuery("a");
        $q->leftJoin("a.sfSimpleForumForum c");
        $q->where("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
        $q->addWhere("a.user_id=?",$user_id);

        return $q->count();
    }
}