<?php

/**
 * sfSimpleForumPostTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfSimpleForumPostTable extends PluginsfSimpleForumPostTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfSimpleForumPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfSimpleForumPost');
    }

    public function getLatestCriteria()
    {
        /*
         * Con esta condición controlo si hay que devolver la consulta sólo para los foros del grupo
         * de consumo o
         */
        if (sfContext::getInstance()->getUser()->getAttribute("forum_type")=="consumer_group")
        {

            $q = $this->createQuery("a");
            $q->leftJoin("a.sfSimpleForumForum c");
            $q->where("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
            $q->orderBy('id DESC');

            return $q;
        }
        else {
            $q = $this->createQuery();
            $q->orderBy('id DESC');

            return $q;
        }
    }

    public function getForForumCriteria($forum_name)
    {
        if (sfContext::getInstance()->getUser()->getAttribute("forum_type")=="consumer_group")
        {
            $q = $this->createQuery("a");
            $q->leftJoin("a.sfSimpleForumForum c");
            $q->where("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
            $q->andWhere('c.slug = ?', array($forum_name));
            $q->orderBy('id DESC');

            return $q;
        }
        else  {
            $q = $this->getLatestCriteria();

            $q->where('sfSimpleForumPost.sfSimpleForumForum.slug = ?', array($forum_name));
            $q->orderBy('id DESC');

            return $q;
        }

    }

    public function getAllPostConsumerGroup()
    {
        $q = $this->createQuery("a");
        $q->leftJoin("a.sfSimpleForumForum c");
        $q->where("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);

        return $q->count();
    }

    public function getForUserCriteria($user_id)
    {
        if (sfContext::getInstance()->getUser()->getAttribute("forum_type")=="consumer_group")
        {
            $q = $this->createQuery("a");
            $q->leftJoin("a.sfSimpleForumForum c");
            $q->where('a.user_id = ?', array($user_id));
            $q->andWhere("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
            $q->orderBy('id DESC');

            return $q;
        }
        else {
            $q = $this->createQuery();
            $q->where('user_id = ?', array($user_id));
            $q->orderBy('id DESC');

            return $q;
        }


    }

    public function getAllPostUserInConsumerGroup($user_id) {
        $q = $this->createQuery("a");
        $q->leftJoin("a.sfSimpleForumForum c");
        $q->where("c.consumer_group_id=?",sfContext::getInstance()->getUser()->getInternalUser()->ConsumerGroup->id);
        $q->addWhere("a.user_id=?",$user_id);

        return $q->count();
    }

}