<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grupos_consumo
 * @subpackage model
 * @author     info@diphda.net
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    var $internal_class;
    var $internal_user;
    
    public function getInternalUser()
    {
        $this->internal_class=$this->Profile->InternalClass->class;
        return $this->internal_user=$this->{$this->internal_class};
    }
}
