<?php use_helper("Form", "My");?>
<div class="wrapper rounded-wrapper semi-width">
  <div class="wrapper-inside">
    <?php echo form_tag("sfGuardAuth/password", array("method"=>"post"));?>
    <h3><?php echo __("Please provide username and email to restore password");?></h3>
    <?php echo content_tag("dfn", __("A new autogenerated password will be sent to email, registered in account"))?>
    <ul>
      <?php echo $form;?>
    </ul>
    <?php echo _submit_tag(__("Restore password"));?>
    </form>
  </div>
</div>