<?php

/**
 * sfWhoIsOnlineUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfWhoIsOnlineUserTable extends PluginsfWhoIsOnlineUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfWhoIsOnlineUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfWhoIsOnlineUser');
    }

    public static function getGuestUsersCount()
    {
        $table = self::getInstance();
        return $table->createQuery()->where("is_user = false")->count();
        
    }
    
    public static function getGuestUsers()
    {
        $table = self::getInstance();
        return $table->createQuery()->where("is_user = false")->execute();
    }

    public static function getLoggedUsersCount()
    {
        $table = self::getInstance();
        return $table->createQuery()->where("is_user = true")->count();
    }
    
    public static function getLoggedUsers()
    {
        $table = self::getInstance();
        $table->createQuery()->where("is_user = true")->execute();
    }
}